/*
 * generated by Xtext 2.31.0
 */
package simplepdl.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSimplePDLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(simplepdl.xtext.simplePDL.SimplePDLPackage.eINSTANCE);
		return result;
	}
}
