/*
 * generated by Xtext 2.31.0
 */
package simplepdl.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimplePDLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("simplepdl/xtext/parser/antlr/internal/InternalSimplePDL.tokens");
	}
}
