/*
 * generated by Xtext 2.31.0
 */
package simplepdl.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import simplepdl.xtext.ui.internal.XtextActivator;

public class SimplePDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("simplepdl.xtext.SimplePDL");
	}

}
