/**
 * generated by Xtext 2.31.0
 */
package simplepdl.xtext.simplePDL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Human</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link simplepdl.xtext.simplePDL.Human#getEmail <em>Email</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.Human#getRole <em>Role</em>}</li>
 * </ul>
 *
 * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getHuman()
 * @model
 * @generated
 */
public interface Human extends Resource
{
  /**
   * Returns the value of the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email</em>' attribute.
   * @see #setEmail(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getHuman_Email()
   * @model
   * @generated
   */
  String getEmail();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.Human#getEmail <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email</em>' attribute.
   * @see #getEmail()
   * @generated
   */
  void setEmail(String value);

  /**
   * Returns the value of the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' attribute.
   * @see #setRole(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getHuman_Role()
   * @model
   * @generated
   */
  String getRole();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.Human#getRole <em>Role</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' attribute.
   * @see #getRole()
   * @generated
   */
  void setRole(String value);

} // Human
