/**
 * generated by Xtext 2.31.0
 */
package simplepdl.xtext.simplePDL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Material</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link simplepdl.xtext.simplePDL.Material#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getMaterial()
 * @model
 * @generated
 */
public interface Material extends Resource
{
  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see #setUnit(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getMaterial_Unit()
   * @model
   * @generated
   */
  String getUnit();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.Material#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see #getUnit()
   * @generated
   */
  void setUnit(String value);

} // Material
