/**
 * generated by Xtext 2.31.0
 */
package simplepdl.xtext.simplePDL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link simplepdl.xtext.simplePDL.Process#getName <em>Name</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.Process#getDescription <em>Description</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.Process#getWorkdefinitions <em>Workdefinitions</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.Process#getWorksequences <em>Worksequences</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.Process#getResources <em>Resources</em>}</li>
 * </ul>
 *
 * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getProcess()
 * @model
 * @generated
 */
public interface Process extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getProcess_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.Process#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getProcess_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.Process#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Workdefinitions</b></em>' containment reference list.
   * The list contents are of type {@link simplepdl.xtext.simplePDL.WorkDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workdefinitions</em>' containment reference list.
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getProcess_Workdefinitions()
   * @model containment="true"
   * @generated
   */
  EList<WorkDefinition> getWorkdefinitions();

  /**
   * Returns the value of the '<em><b>Worksequences</b></em>' containment reference list.
   * The list contents are of type {@link simplepdl.xtext.simplePDL.WorkSequence}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Worksequences</em>' containment reference list.
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getProcess_Worksequences()
   * @model containment="true"
   * @generated
   */
  EList<WorkSequence> getWorksequences();

  /**
   * Returns the value of the '<em><b>Resources</b></em>' containment reference list.
   * The list contents are of type {@link simplepdl.xtext.simplePDL.Resource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resources</em>' containment reference list.
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getProcess_Resources()
   * @model containment="true"
   * @generated
   */
  EList<Resource> getResources();

} // Process
