/**
 * generated by Xtext 2.31.0
 */
package simplepdl.xtext.simplePDL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see simplepdl.xtext.simplePDL.SimplePDLFactory
 * @model kind="package"
 * @generated
 */
public interface SimplePDLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "simplePDL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.simplepdl/SimplePDL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "simplePDL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimplePDLPackage eINSTANCE = simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl.init();

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.ModelImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Processes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PROCESSES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.ProcessImpl <em>Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.ProcessImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getProcess()
   * @generated
   */
  int PROCESS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Workdefinitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__WORKDEFINITIONS = 2;

  /**
   * The feature id for the '<em><b>Worksequences</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__WORKSEQUENCES = 3;

  /**
   * The feature id for the '<em><b>Resources</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__RESOURCES = 4;

  /**
   * The number of structural features of the '<em>Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.WorkDefinitionImpl <em>Work Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.WorkDefinitionImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkDefinition()
   * @generated
   */
  int WORK_DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Assigned To</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__ASSIGNED_TO = 2;

  /**
   * The feature id for the '<em><b>Required Materials</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__REQUIRED_MATERIALS = 3;

  /**
   * The feature id for the '<em><b>Predecessor</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__PREDECESSOR = 4;

  /**
   * The feature id for the '<em><b>Pred Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__PRED_TYPE = 5;

  /**
   * The feature id for the '<em><b>Successor</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__SUCCESSOR = 6;

  /**
   * The feature id for the '<em><b>Succ Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION__SUCC_TYPE = 7;

  /**
   * The number of structural features of the '<em>Work Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_DEFINITION_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.WorkSequenceImpl <em>Work Sequence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.WorkSequenceImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkSequence()
   * @generated
   */
  int WORK_SEQUENCE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__NAME = 0;

  /**
   * The feature id for the '<em><b>Predecessor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__PREDECESSOR = 1;

  /**
   * The feature id for the '<em><b>Successor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__SUCCESSOR = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE__TYPE = 3;

  /**
   * The number of structural features of the '<em>Work Sequence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORK_SEQUENCE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.RequiredMaterialImpl <em>Required Material</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.RequiredMaterialImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getRequiredMaterial()
   * @generated
   */
  int REQUIRED_MATERIAL = 4;

  /**
   * The feature id for the '<em><b>Material</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_MATERIAL__MATERIAL = 0;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_MATERIAL__QUANTITY = 1;

  /**
   * The number of structural features of the '<em>Required Material</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_MATERIAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.ResourceImpl <em>Resource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.ResourceImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getResource()
   * @generated
   */
  int RESOURCE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE__NAME = 0;

  /**
   * The number of structural features of the '<em>Resource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESOURCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.HumanImpl <em>Human</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.HumanImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getHuman()
   * @generated
   */
  int HUMAN = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HUMAN__NAME = RESOURCE__NAME;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HUMAN__EMAIL = RESOURCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HUMAN__ROLE = RESOURCE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Human</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HUMAN_FEATURE_COUNT = RESOURCE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.impl.MaterialImpl <em>Material</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.impl.MaterialImpl
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getMaterial()
   * @generated
   */
  int MATERIAL = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATERIAL__NAME = RESOURCE__NAME;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATERIAL__UNIT = RESOURCE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Material</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATERIAL_FEATURE_COUNT = RESOURCE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link simplepdl.xtext.simplePDL.WorkSequenceType <em>Work Sequence Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see simplepdl.xtext.simplePDL.WorkSequenceType
   * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkSequenceType()
   * @generated
   */
  int WORK_SEQUENCE_TYPE = 8;


  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see simplepdl.xtext.simplePDL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link simplepdl.xtext.simplePDL.Model#getProcesses <em>Processes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Processes</em>'.
   * @see simplepdl.xtext.simplePDL.Model#getProcesses()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Processes();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.Process <em>Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process</em>'.
   * @see simplepdl.xtext.simplePDL.Process
   * @generated
   */
  EClass getProcess();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.Process#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see simplepdl.xtext.simplePDL.Process#getName()
   * @see #getProcess()
   * @generated
   */
  EAttribute getProcess_Name();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.Process#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see simplepdl.xtext.simplePDL.Process#getDescription()
   * @see #getProcess()
   * @generated
   */
  EAttribute getProcess_Description();

  /**
   * Returns the meta object for the containment reference list '{@link simplepdl.xtext.simplePDL.Process#getWorkdefinitions <em>Workdefinitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Workdefinitions</em>'.
   * @see simplepdl.xtext.simplePDL.Process#getWorkdefinitions()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_Workdefinitions();

  /**
   * Returns the meta object for the containment reference list '{@link simplepdl.xtext.simplePDL.Process#getWorksequences <em>Worksequences</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Worksequences</em>'.
   * @see simplepdl.xtext.simplePDL.Process#getWorksequences()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_Worksequences();

  /**
   * Returns the meta object for the containment reference list '{@link simplepdl.xtext.simplePDL.Process#getResources <em>Resources</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Resources</em>'.
   * @see simplepdl.xtext.simplePDL.Process#getResources()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_Resources();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.WorkDefinition <em>Work Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Work Definition</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition
   * @generated
   */
  EClass getWorkDefinition();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.WorkDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition#getName()
   * @see #getWorkDefinition()
   * @generated
   */
  EAttribute getWorkDefinition_Name();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.WorkDefinition#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition#getDescription()
   * @see #getWorkDefinition()
   * @generated
   */
  EAttribute getWorkDefinition_Description();

  /**
   * Returns the meta object for the reference list '{@link simplepdl.xtext.simplePDL.WorkDefinition#getAssignedTo <em>Assigned To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Assigned To</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition#getAssignedTo()
   * @see #getWorkDefinition()
   * @generated
   */
  EReference getWorkDefinition_AssignedTo();

  /**
   * Returns the meta object for the containment reference list '{@link simplepdl.xtext.simplePDL.WorkDefinition#getRequiredMaterials <em>Required Materials</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Required Materials</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition#getRequiredMaterials()
   * @see #getWorkDefinition()
   * @generated
   */
  EReference getWorkDefinition_RequiredMaterials();

  /**
   * Returns the meta object for the reference list '{@link simplepdl.xtext.simplePDL.WorkDefinition#getPredecessor <em>Predecessor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Predecessor</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition#getPredecessor()
   * @see #getWorkDefinition()
   * @generated
   */
  EReference getWorkDefinition_Predecessor();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.WorkDefinition#getPredType <em>Pred Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pred Type</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition#getPredType()
   * @see #getWorkDefinition()
   * @generated
   */
  EAttribute getWorkDefinition_PredType();

  /**
   * Returns the meta object for the reference list '{@link simplepdl.xtext.simplePDL.WorkDefinition#getSuccessor <em>Successor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Successor</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition#getSuccessor()
   * @see #getWorkDefinition()
   * @generated
   */
  EReference getWorkDefinition_Successor();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.WorkDefinition#getSuccType <em>Succ Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Succ Type</em>'.
   * @see simplepdl.xtext.simplePDL.WorkDefinition#getSuccType()
   * @see #getWorkDefinition()
   * @generated
   */
  EAttribute getWorkDefinition_SuccType();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.WorkSequence <em>Work Sequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Work Sequence</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequence
   * @generated
   */
  EClass getWorkSequence();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.WorkSequence#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequence#getName()
   * @see #getWorkSequence()
   * @generated
   */
  EAttribute getWorkSequence_Name();

  /**
   * Returns the meta object for the reference '{@link simplepdl.xtext.simplePDL.WorkSequence#getPredecessor <em>Predecessor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Predecessor</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequence#getPredecessor()
   * @see #getWorkSequence()
   * @generated
   */
  EReference getWorkSequence_Predecessor();

  /**
   * Returns the meta object for the reference '{@link simplepdl.xtext.simplePDL.WorkSequence#getSuccessor <em>Successor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Successor</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequence#getSuccessor()
   * @see #getWorkSequence()
   * @generated
   */
  EReference getWorkSequence_Successor();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.WorkSequence#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequence#getType()
   * @see #getWorkSequence()
   * @generated
   */
  EAttribute getWorkSequence_Type();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.RequiredMaterial <em>Required Material</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Required Material</em>'.
   * @see simplepdl.xtext.simplePDL.RequiredMaterial
   * @generated
   */
  EClass getRequiredMaterial();

  /**
   * Returns the meta object for the reference '{@link simplepdl.xtext.simplePDL.RequiredMaterial#getMaterial <em>Material</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Material</em>'.
   * @see simplepdl.xtext.simplePDL.RequiredMaterial#getMaterial()
   * @see #getRequiredMaterial()
   * @generated
   */
  EReference getRequiredMaterial_Material();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.RequiredMaterial#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantity</em>'.
   * @see simplepdl.xtext.simplePDL.RequiredMaterial#getQuantity()
   * @see #getRequiredMaterial()
   * @generated
   */
  EAttribute getRequiredMaterial_Quantity();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.Resource <em>Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Resource</em>'.
   * @see simplepdl.xtext.simplePDL.Resource
   * @generated
   */
  EClass getResource();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.Resource#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see simplepdl.xtext.simplePDL.Resource#getName()
   * @see #getResource()
   * @generated
   */
  EAttribute getResource_Name();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.Human <em>Human</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Human</em>'.
   * @see simplepdl.xtext.simplePDL.Human
   * @generated
   */
  EClass getHuman();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.Human#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see simplepdl.xtext.simplePDL.Human#getEmail()
   * @see #getHuman()
   * @generated
   */
  EAttribute getHuman_Email();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.Human#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role</em>'.
   * @see simplepdl.xtext.simplePDL.Human#getRole()
   * @see #getHuman()
   * @generated
   */
  EAttribute getHuman_Role();

  /**
   * Returns the meta object for class '{@link simplepdl.xtext.simplePDL.Material <em>Material</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Material</em>'.
   * @see simplepdl.xtext.simplePDL.Material
   * @generated
   */
  EClass getMaterial();

  /**
   * Returns the meta object for the attribute '{@link simplepdl.xtext.simplePDL.Material#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see simplepdl.xtext.simplePDL.Material#getUnit()
   * @see #getMaterial()
   * @generated
   */
  EAttribute getMaterial_Unit();

  /**
   * Returns the meta object for enum '{@link simplepdl.xtext.simplePDL.WorkSequenceType <em>Work Sequence Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Work Sequence Type</em>'.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType
   * @generated
   */
  EEnum getWorkSequenceType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SimplePDLFactory getSimplePDLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.ModelImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Processes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PROCESSES = eINSTANCE.getModel_Processes();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.ProcessImpl <em>Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.ProcessImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getProcess()
     * @generated
     */
    EClass PROCESS = eINSTANCE.getProcess();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS__NAME = eINSTANCE.getProcess_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS__DESCRIPTION = eINSTANCE.getProcess_Description();

    /**
     * The meta object literal for the '<em><b>Workdefinitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__WORKDEFINITIONS = eINSTANCE.getProcess_Workdefinitions();

    /**
     * The meta object literal for the '<em><b>Worksequences</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__WORKSEQUENCES = eINSTANCE.getProcess_Worksequences();

    /**
     * The meta object literal for the '<em><b>Resources</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__RESOURCES = eINSTANCE.getProcess_Resources();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.WorkDefinitionImpl <em>Work Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.WorkDefinitionImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkDefinition()
     * @generated
     */
    EClass WORK_DEFINITION = eINSTANCE.getWorkDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_DEFINITION__NAME = eINSTANCE.getWorkDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_DEFINITION__DESCRIPTION = eINSTANCE.getWorkDefinition_Description();

    /**
     * The meta object literal for the '<em><b>Assigned To</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_DEFINITION__ASSIGNED_TO = eINSTANCE.getWorkDefinition_AssignedTo();

    /**
     * The meta object literal for the '<em><b>Required Materials</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_DEFINITION__REQUIRED_MATERIALS = eINSTANCE.getWorkDefinition_RequiredMaterials();

    /**
     * The meta object literal for the '<em><b>Predecessor</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_DEFINITION__PREDECESSOR = eINSTANCE.getWorkDefinition_Predecessor();

    /**
     * The meta object literal for the '<em><b>Pred Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_DEFINITION__PRED_TYPE = eINSTANCE.getWorkDefinition_PredType();

    /**
     * The meta object literal for the '<em><b>Successor</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_DEFINITION__SUCCESSOR = eINSTANCE.getWorkDefinition_Successor();

    /**
     * The meta object literal for the '<em><b>Succ Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_DEFINITION__SUCC_TYPE = eINSTANCE.getWorkDefinition_SuccType();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.WorkSequenceImpl <em>Work Sequence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.WorkSequenceImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkSequence()
     * @generated
     */
    EClass WORK_SEQUENCE = eINSTANCE.getWorkSequence();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_SEQUENCE__NAME = eINSTANCE.getWorkSequence_Name();

    /**
     * The meta object literal for the '<em><b>Predecessor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_SEQUENCE__PREDECESSOR = eINSTANCE.getWorkSequence_Predecessor();

    /**
     * The meta object literal for the '<em><b>Successor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORK_SEQUENCE__SUCCESSOR = eINSTANCE.getWorkSequence_Successor();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORK_SEQUENCE__TYPE = eINSTANCE.getWorkSequence_Type();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.RequiredMaterialImpl <em>Required Material</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.RequiredMaterialImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getRequiredMaterial()
     * @generated
     */
    EClass REQUIRED_MATERIAL = eINSTANCE.getRequiredMaterial();

    /**
     * The meta object literal for the '<em><b>Material</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIRED_MATERIAL__MATERIAL = eINSTANCE.getRequiredMaterial_Material();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REQUIRED_MATERIAL__QUANTITY = eINSTANCE.getRequiredMaterial_Quantity();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.ResourceImpl <em>Resource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.ResourceImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getResource()
     * @generated
     */
    EClass RESOURCE = eINSTANCE.getResource();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESOURCE__NAME = eINSTANCE.getResource_Name();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.HumanImpl <em>Human</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.HumanImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getHuman()
     * @generated
     */
    EClass HUMAN = eINSTANCE.getHuman();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HUMAN__EMAIL = eINSTANCE.getHuman_Email();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HUMAN__ROLE = eINSTANCE.getHuman_Role();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.impl.MaterialImpl <em>Material</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.impl.MaterialImpl
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getMaterial()
     * @generated
     */
    EClass MATERIAL = eINSTANCE.getMaterial();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATERIAL__UNIT = eINSTANCE.getMaterial_Unit();

    /**
     * The meta object literal for the '{@link simplepdl.xtext.simplePDL.WorkSequenceType <em>Work Sequence Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see simplepdl.xtext.simplePDL.WorkSequenceType
     * @see simplepdl.xtext.simplePDL.impl.SimplePDLPackageImpl#getWorkSequenceType()
     * @generated
     */
    EEnum WORK_SEQUENCE_TYPE = eINSTANCE.getWorkSequenceType();

  }

} //SimplePDLPackage
