/**
 * generated by Xtext 2.31.0
 */
package simplepdl.xtext.simplePDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Sequence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkSequence#getName <em>Name</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkSequence#getPredecessor <em>Predecessor</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkSequence#getSuccessor <em>Successor</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkSequence#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkSequence()
 * @model
 * @generated
 */
public interface WorkSequence extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkSequence_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkSequence#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Predecessor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predecessor</em>' reference.
   * @see #setPredecessor(WorkDefinition)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkSequence_Predecessor()
   * @model
   * @generated
   */
  WorkDefinition getPredecessor();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkSequence#getPredecessor <em>Predecessor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predecessor</em>' reference.
   * @see #getPredecessor()
   * @generated
   */
  void setPredecessor(WorkDefinition value);

  /**
   * Returns the value of the '<em><b>Successor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Successor</em>' reference.
   * @see #setSuccessor(WorkDefinition)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkSequence_Successor()
   * @model
   * @generated
   */
  WorkDefinition getSuccessor();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkSequence#getSuccessor <em>Successor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Successor</em>' reference.
   * @see #getSuccessor()
   * @generated
   */
  void setSuccessor(WorkDefinition value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link simplepdl.xtext.simplePDL.WorkSequenceType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType
   * @see #setType(WorkSequenceType)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkSequence_Type()
   * @model
   * @generated
   */
  WorkSequenceType getType();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkSequence#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType
   * @see #getType()
   * @generated
   */
  void setType(WorkSequenceType value);

} // WorkSequence
