/**
 * generated by Xtext 2.31.0
 */
package simplepdl.xtext.simplePDL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkDefinition#getName <em>Name</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkDefinition#getDescription <em>Description</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkDefinition#getAssignedTo <em>Assigned To</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkDefinition#getRequiredMaterials <em>Required Materials</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkDefinition#getPredecessor <em>Predecessor</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkDefinition#getPredType <em>Pred Type</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkDefinition#getSuccessor <em>Successor</em>}</li>
 *   <li>{@link simplepdl.xtext.simplePDL.WorkDefinition#getSuccType <em>Succ Type</em>}</li>
 * </ul>
 *
 * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkDefinition()
 * @model
 * @generated
 */
public interface WorkDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkDefinition_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkDefinition#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Assigned To</b></em>' reference list.
   * The list contents are of type {@link simplepdl.xtext.simplePDL.Human}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assigned To</em>' reference list.
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkDefinition_AssignedTo()
   * @model
   * @generated
   */
  EList<Human> getAssignedTo();

  /**
   * Returns the value of the '<em><b>Required Materials</b></em>' containment reference list.
   * The list contents are of type {@link simplepdl.xtext.simplePDL.RequiredMaterial}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required Materials</em>' containment reference list.
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkDefinition_RequiredMaterials()
   * @model containment="true"
   * @generated
   */
  EList<RequiredMaterial> getRequiredMaterials();

  /**
   * Returns the value of the '<em><b>Predecessor</b></em>' reference list.
   * The list contents are of type {@link simplepdl.xtext.simplePDL.WorkDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predecessor</em>' reference list.
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkDefinition_Predecessor()
   * @model
   * @generated
   */
  EList<WorkDefinition> getPredecessor();

  /**
   * Returns the value of the '<em><b>Pred Type</b></em>' attribute.
   * The literals are from the enumeration {@link simplepdl.xtext.simplePDL.WorkSequenceType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pred Type</em>' attribute.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType
   * @see #setPredType(WorkSequenceType)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkDefinition_PredType()
   * @model
   * @generated
   */
  WorkSequenceType getPredType();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkDefinition#getPredType <em>Pred Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pred Type</em>' attribute.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType
   * @see #getPredType()
   * @generated
   */
  void setPredType(WorkSequenceType value);

  /**
   * Returns the value of the '<em><b>Successor</b></em>' reference list.
   * The list contents are of type {@link simplepdl.xtext.simplePDL.WorkDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Successor</em>' reference list.
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkDefinition_Successor()
   * @model
   * @generated
   */
  EList<WorkDefinition> getSuccessor();

  /**
   * Returns the value of the '<em><b>Succ Type</b></em>' attribute.
   * The literals are from the enumeration {@link simplepdl.xtext.simplePDL.WorkSequenceType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Succ Type</em>' attribute.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType
   * @see #setSuccType(WorkSequenceType)
   * @see simplepdl.xtext.simplePDL.SimplePDLPackage#getWorkDefinition_SuccType()
   * @model
   * @generated
   */
  WorkSequenceType getSuccType();

  /**
   * Sets the value of the '{@link simplepdl.xtext.simplePDL.WorkDefinition#getSuccType <em>Succ Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Succ Type</em>' attribute.
   * @see simplepdl.xtext.simplePDL.WorkSequenceType
   * @see #getSuccType()
   * @generated
   */
  void setSuccType(WorkSequenceType value);

} // WorkDefinition
