/*
 * generated by Xtext 2.31.0
 */
package simplepdl.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSimplePDLScopeProvider extends DelegatingScopeProvider {
}
