<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simplepdl" nsURI="http://www.example.org/simplepdl" nsPrefix="simplepdl">
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processElements" upperBound="-1"
        eType="#//ProcessElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkDefinition" eSuperTypes="#//ProcessElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksToSuccessor" upperBound="-1"
        eType="#//WorkSequence" eOpposite="#//WorkSequence/predecessor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksToPredecessor" upperBound="-1"
        eType="#//WorkSequence" eOpposite="#//WorkSequence/successor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTo" lowerBound="1"
        upperBound="-1" eType="#//Human" eOpposite="#//Human/asignedTasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredmaterial" upperBound="-1"
        eType="#//RequiredMaterial" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkSequence" eSuperTypes="#//ProcessElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkType" lowerBound="1"
        eType="#//WorkSequenceType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" lowerBound="1"
        eType="#//WorkDefinition" eOpposite="#//WorkDefinition/linksToSuccessor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" lowerBound="1"
        eType="#//WorkDefinition" eOpposite="#//WorkDefinition/linksToPredecessor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WorkSequenceType">
    <eLiterals name="startToStart"/>
    <eLiterals name="finishToStart"/>
    <eLiterals name="startToFinish"/>
    <eLiterals name="finishToFInish"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Human" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asignedTasks" upperBound="-1"
        eType="#//WorkDefinition" eOpposite="#//WorkDefinition/assignedTo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Material" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredMaterial">
    <eStructuralFeatures xsi:type="ecore:EReference" name="material" eType="#//Material"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
  </eClassifiers>
</ecore:EPackage>
